//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue()
        {
            this.IssueHistories = new HashSet<IssueHistory>();
        }
    
        public int IssueId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public string Priority { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.Guid> AssignedTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string AssignedToUsername { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string CountryId { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual IssueCategory IssueCategory { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueHistory> IssueHistories { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
