//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueHistory
    {
        public int HistoryId { get; set; }
        public int IssueId { get; set; }
        public int StatusId { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string Comments { get; set; }
        public string StatusName { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Status Status { get; set; }
    }
}
