//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEFSUser
    {
        public int Id { get; set; }
        public string uid { get; set; }
        public string u_account { get; set; }
        public string u_firstname { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public string m_country { get; set; }
        public string m_region { get; set; }
        public string m_report { get; set; }
        public string m_tier { get; set; }
        public string panelist_code { get; set; }
        public string pstatus_date { get; set; }
        public string last_mod_date { get; set; }
        public string md_status { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
    }
}
